### ISSUE TITLE
Installing on 4.5.2, bare metal install, with .7z version - java exception

### ISSUE THREAD

**Issue by jwhowa-rp** [odoodo/Mirth-Migrator#14]
Hi All:

I've tried to install this (after finding the .7z version which includes the jar) but after setting everything up, I see this when I visit the url:

```
java.io.FileNotFoundException: .\web\MirthMigrator\html\index.html (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at com.mirth.connect.connectors.http.HttpReceiver$StaticResourceHandler.handle(HttpReceiver.java:728)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

The channel deploys correctly and I can see the library active inside Mirth, the web app just does not respond.  Only deviation from the documentation is that I have opened up permissions to be less restrictive (index.html = 777) for testing.

Any assistance would be greatly appreciated!
-Jim Howard

**Comment by jwhowa-rp** [comment]
If anyone cares, I resolved this.  The problem is that the documentation and the code uses backslashes (\) per microsoft standard.  I use ubuntu, where forward slashes (/) are standard so I just fixed the .\wrong\path\backslashes with ./right/path/slashes and the channel and gui come up.

Now what!?!?!? :)

The documentation is sparse lol.

**Comment by odoodo** [comment]
Indead this was an issue with the initial version. 

Please use the latest version ([v1.02](https://github.com/odoodo/Mirth-Migrator/releases/download/1.0.2/MirthMigrator-v1.0.2.zip) at the time of writing) This version fixes this issue as well as some others.

The latest version can be always found [here](https://github.com/odoodo/Mirth-Migrator/releases)

**Comment by odoodo** [comment]
A [How to get started thread](https://github.com/odoodo/Mirth-Migrator/discussions/15) describing the initial configuration and selection of the components has been created in the Discussion section. Documentation will be extended as whenever I find some time.

**Comment by jwhowa-rp** [comment]
I was in fact using the latest version, lucky break. :)

However, I am unable to add a Mirth Instance.  Once I log in to MirthMigrator and add a single mirth instance, then hit the "X" to save my config, I get a giant red triangle, and error 200, as so:

![Image](https://github.com/user-attachments/assets/c106ac62-1586-48b8-b7be-a64c5bd35fc0)

Any suggestion what I might have configured wrong to make this happen?

Thanks again!  BTW I am running on Mirth 4.5.2 if that is of interest.

-Jim

**Comment by odoodo** [comment]
Mirth 4.5.2 should be fine.

Are you really sure you are using the latest Version? (I am wondering because the latest Version is not shipped as 7zip but as a ZIP archive...)
What error is displayed in the Mirth channel? Does mirth has write permissions to <Your Mirth Installation>/web/MirthMigrator/config?

**Comment by jwhowa-rp** [comment]
Definitely using the latest.  .7z was earlier yesterday, I found the latest zip and upgraded.  Yes, mirth has permissions to write to /web/MirthMigrator/config, but there is nothing in that directory, so I reckon it hasn't tried yet.  I just get the giant warning triangle when I try to save a mirth instance.  

Any advice?  And thank you for the replies!

**Comment by pacmano1** [comment]
from: https://github.com/nextgenhealthcare/connect/discussions/6345

![Image](https://github.com/user-attachments/assets/6b8b4f5c-03c6-4045-8450-a5a520e906e4)

**Comment by pacmano1** [comment]
https://github.com/odoodo/Mirth-Migrator/releases/download/1.0.2/MirthMigrator-v1.0.2.zip

**Comment by pacmano1** [comment]
@odoodo I get the same error.   4.5.0.  Just installed it.

**Comment by pacmano1** [comment]
@odoodo I get this same error after initial login adding a server, then click "X" on the upper right.

note console:

![Image](https://github.com/user-attachments/assets/d6209b14-b0d3-4a2a-80e9-70d710752584)

**Comment by pacmano1** [comment]
of note also:
```
"Corrupt configuration: \nThe Mirth Migrator configuration file \"/usr/local/mirthconnect/.\\web\\MirthMigrator\\config\\MirthMigration.conf\" is missing."
```

**Comment by jwhowa-rp** [comment]
> For others reading this thread of cousre, [@jwhowa-rp](https://github.com/jwhowa-rp) mentioned he did grab the latest.

Thank you I definitely buried the lead! :)

**Comment by odoodo** [comment]
This seems to be another issue w/ non-windows-based systems (unfortunately I currently do not have access to non-windows Mirth installations).

I changed the way of configuration file handling. It would be great if someone could replace the MirthMigrator.jar with [this build](https://github.com/user-attachments/files/18697046/MirthMigrator.jar.zip) and let me know if this solved the issue. (please unzip first as github does not allow to upload jars directly)

**Comment by jwhowa-rp** [comment]
That actually made it worse... Now I get the big triangle IMMEDIATELY when logging in:

![Image](https://github.com/user-attachments/assets/7e7e0e9b-4dcb-4807-8c62-7872cd993953)

**Comment by jwhowa-rp** [comment]
[padasarthqs01|/opt/mirthconnect/web/MirthMigrator/jar:$] ERROR 2025-02-06 21:03:28.157 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (5178912312341a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] lu.hrs.mirth.migration.MirthMigrator: We got an Oooopsi!
invalid stored block lengths
ERROR 2025-02-06 21:03:28.157 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: java.util.zip.ZipException: invalid stored block lengths
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
ERROR 2025-02-06 21:03:28.158 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.io.Reader.read(Reader.java:140)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1610)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1589)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1384)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1153)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.apache.commons.io.IOUtils.toString(IOUtils.java:3105)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.apache.commons.io.IOUtils.toString(IOUtils.java:3133)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at lu.hrs.mirth.migration.MirthMigrator.getConfiguration(MirthMigrator.java:3565)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERROR 2025-02-06 21:03:28.159 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.lang.reflect.Method.invoke(Method.java:498)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
ERROR 2025-02-06 21:03:28.160 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
ERROR 2025-02-06 21:03:28.161 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
ERROR 2025-02-06 21:03:28.161 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:151)
ERROR 2025-02-06 21:03:28.161 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.doCall(JavaScriptFilterTransformer.java:224)
ERROR 2025-02-06 21:03:28.161 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.doCall(JavaScriptFilterTransformer.java:187)
ERROR 2025-02-06 21:03:28.161 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:114)
ERROR 2025-02-06 21:03:28.162 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ERROR 2025-02-06 21:03:28.162 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ERROR 2025-02-06 21:03:28.162 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ERROR 2025-02-06 21:03:28.162 [Destination Filter/Transformer JavaScript Task on MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f), getConfiguration (10) < pool-1-thread-14] Server: 	at java.lang.Thread.run(Thread.java:750)

**Comment by pacmano1** [comment]
> This seems to be another issue w/ non-windows-based systems (unfortunately I currently do not have access to non-windows Mirth installations).

Well that is fixable with a VM or container and a download.

**Comment by odoodo** [comment]
Seems to be pointing to a promissing direction ;-)

Double check if the configuration of testmirth is correct:

- Does the server name (IPs are currently not supported) correspond to the actual Mirth instance? 
- Is the port the correct port of the Mirth API? (default port at installing Mirth is 8443)
- Does the configured account exist on the testmirth instance? Is the password correct?

If the answer to all these questions is yes, make Mirth Migrator talk by changing the log level of the library and the channel.

**Comment by jwhowa-rp** [comment]
> * Does the server name (IPs are currently not supported) correspond to the actual Mirth instance?

AH, no, I was using ip just in case DNS wasn't supported.  To be clear, is the name in that field supposed to be the "Mirth" server name (from inside the gui) or the DNS name of the node/pod/whatever is running Mirth?

> * Does the configured account exist on the testmirth instance? Is the password correct?

Yes.

**Comment by odoodo** [comment]
> To be clear, is the name in that field supposed to be the "Mirth" server name (from inside the gui) or the DNS name of the node/pod/whatever is running Mirth?

It must be the same name and port you would use in the Mirth Administrator Launcher for starting the Mirth Administrator for a Mirth instance.

**Comment by pacmano1** [comment]
will a bit further, but:

![Image](https://github.com/user-attachments/assets/b66d73df-2af3-4448-9997-4d7ade0040bd)

**Comment by pacmano1** [comment]
ah... getting further now but spinning trying to load - there are 650 channels

**Comment by pacmano1** [comment]
code templates to load.

**Comment by jwhowa-rp** [comment]
Over here on Linux the nodename made a difference, but new error now...

The testmirth server (with correct un/pw) are chooseable from the list, but as soon as you choose it, you get this error:

![Image](https://github.com/user-attachments/assets/00c4b161-4e12-4366-b876-1f20ba9d815c)

Whether or not it's channels or code templates, same issue.

@pacmano1 I have about 400 channels on each of my Mirth servers too, so it will be interesting to see how it handles that much code!

**Comment by pacmano1** [comment]
my hostname and mirth..settings..Server Name is mirth391.

I have local hosts file entries for that name also on the server running mirth and my local workstation.

**Comment by odoodo** [comment]
> it does not like hundreds of channels.

This should not be a problem. Well, we are currently operating about 150 - 200 channels per server. But I just migrated more than 400 channels to an old test instance and it works w/o any issues:
![Image](https://github.com/user-attachments/assets/24657363-7ea9-487d-bc1e-69b6bca33982)
Caching took about 10 seconds but that should be about the same amount of time Mirth Administrator would need to cache channel information

**Comment by pacmano1** [comment]
I had 625 channel and hundreds of code templates.   It would eventually give that 200 error.

**Comment by odoodo** [comment]
> I had 625 channel and hundreds of code templates. It would eventually give that 200 error.

What do you mean by "200 error"? (HTTP return code 200 would mean everything is ok) Did you try to increase the log level of the channel and the library? This should show some helpful hints in the channel/log.

**Comment by pacmano1** [comment]
sorry, my comment was useless, lol.  Let me get some screenshots tomorrow.  Serves me right for using my phone while I'm not of a computer.

**Comment by odoodo** [comment]
I discovered a potential race condition, which might have caused your issues. Please [install this Mirth Migrator version](https://github.com/user-attachments/files/18724460/MirthMigrator-v1.0.3-build_20250209.zip), which (hopefully) solves your issues.

Handling of several hundreds of channel and code templates worked flawlessly for me and caching was much faster compared to Mirth Administrator.

Please let me know if this build did do the trick. If this is the case, I'll release a new version.

**Comment by pacmano1** [comment]
Just spins forever when trying to load channels, then dies:


```
ERROR 2025-02-09 14:59:43.238 [Channel DeployTask Thread on (51789745-f3c2-41a8-b631-cc44c640d22f) < pool-7-thread-2] com.mirth.connect.donkey.server.channel.Channel: Startup recovery interrupted for channel MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f)
java.lang.InterruptedException: null
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:471) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:190) ~[?:?]
	at com.mirth.connect.donkey.server.channel.Channel.processUnfinishedMessages(Channel.java:1931) ~[donkey-server.jar:?]
	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:739) ~[donkey-server.jar:?]
	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:2031) ~[mirth-server.jar:?]
	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.execute(DonkeyEngineController.java:1835) ~[mirth-server.jar:?]
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:67) ~[mirth-server.jar:?]
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16) ~[mirth-server.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
ERROR 2025-02-09 14:59:43.240 [Channel DeployTask Thread on (51789745-f3c2-41a8-b631-cc44c640d22f) < pool-7-thread-2] com.mirth.connect.server.channel.ErrorTaskHandler: com.mirth.connect.donkey.server.StartException: Start channel task for MIRTH_MIGRATOR (51789745-f3c2-41a8-b631-cc44c640d22f) terminated by halt notification.
	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:777)
	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:2031)
	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.execute(DonkeyEngineController.java:1835)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:67)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:471)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at com.mirth.connect.donkey.server.channel.Channel.processUnfinishedMessages(Channel.java:1931)
	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:739)
	... 8 more
```

![Image](https://github.com/user-attachments/assets/b7641a26-e163-4e7f-870a-507757ca050c)

**Comment by odoodo** [comment]
Wow - that was a good catch! 

It looks like you named a channel or with just a number. It actually did not came to my mind that someone would do that, lol. In this case, the name would be parsed as a number instead of a String when transferred to JSON and cause this exception when the attribute is requested as String.

I applied a fix and it would be great if you could retest with [this version of the library](https://github.com/user-attachments/files/18737687/MirthMigrator-NumberIssueFix.zip). (please restart your Mirth instance after replacing the library because of Mirth faulty custom class loader)

**Comment by pacmano1** [comment]
That did work.  And it did load quickly.

Notes:

1. I would have mouse over for the icons in the middle (e.g. "Diff", "Refresh", "Prep to Move").   
2. I am not clear on how to select different channels - it seems to auth match which is great, but I want to be able to select a different named channel
3. Multi-select works but it is not clear would a diff would do so maybe that should be greyed out?

**Comment by odoodo** [comment]
Great!

1. ok
2. I am not sure if I got you right but the compare automatically compares both instances of a component (channel or code function or code template) if it exists on both systems that have been selected. So you would like to compare different channels instead of different versions of the same channel?
3. indeed, makes sense

**Comment by pacmano1** [comment]
Yes on number 2.

Because I might be working in dev and call a channel  `<some name>-dev` as an example.

**Comment by jwhowa-rp** [comment]
Hey Gents, it started working for me (on small servers) with one of your recent updates.  I am now running the latest one from this chat, and I can confirm it works on small servers, but when I throw it at a big server (650 channels, 450 active) it gags, like this:

![Image](https://github.com/user-attachments/assets/afeb8473-7e49-4c05-b9ab-59533a3e37a8)

I assume it's just a timeout issue or something.  Does that sound like a simple fix?

**Comment by odoodo** [comment]
> I assume it's just a timeout issue or something. Does that sound like a simple fix?

650 channels should not  be an issue but admittedly I don't have more than roughly 500 channels at hand for testing.

Please increase the log level of the Mirth channel (set it to "Development" in the general tab) and post the content of the error tab for the failing message.

**Comment by jwhowa-rp** [comment]
Looks like heap space is getting me:

Transformer error
ERROR MESSAGE: Error evaluating transformer
java.lang.OutOfMemoryError: Java heap space

And yes, I used the jar with the number fix...

**Comment by jwhowa-rp** [comment]
My channels are pretty huge, and there are a LOT of them.  It takes Mirth Admin launcher about 1GB of local RAM on my PC for each server I load up, FWIW.

**Comment by jwhowa-rp** [comment]
In testing smaller servers, the sync feature works great. However, adding an option to choose between just syncing or syncing and deploying would be useful.

Maybe something as simple as a "deploy after syncing" checkbox could allow for immediate deployment after syncing, enhancing workflow efficiency.

Just a thought.

Anyway, thank you for putting this out there and actively developing it!

**Comment by pacmano1** [comment]
Look at you getting all fancy with a deploy after migrate.  

All kidding aside, you would probably want the status of that action otherwse you gotta go look anyway.

**Comment by jwhowa-rp** [comment]
> Look at you getting all fancy with a deploy after migrate.
> 
> All kidding aside, you would probably want the status of that action otherwse you gotta go look anyway.

hehe hey, a fella can dream... :)

I have scripts that handle my repo and channel promotions, and yes I deploy programatically. :)  There is one "outlying" scenario that won't work with my scripts, but we manually do those.  

I am a very very lazy release manager. :) Why do something I can automate? :D

Anyway this tool has potential to be crazy useful to me, it's been a fun project so far.

**Comment by odoodo** [comment]
> Looks like heap space is getting me:
> 
> Transformer error ERROR MESSAGE: Error evaluating transformer java.lang.OutOfMemoryError: Java heap space

Increasing the service heap space in mcservice.vmoptions respective mcserver.vmoptions should fix this.

Please place any feature request/proposition in a new issue.

**Comment by jwhowa-rp** [comment]
> > Looks like heap space is getting me:
> > Transformer error ERROR MESSAGE: Error evaluating transformer java.lang.OutOfMemoryError: Java heap space

I've been gradually increasing the service heap space, currently up to 4GB, yet I'm still encountering the 200 error after a 5-6 second delay. Here's the pattern:

Small Server: When I select the server, there's a brief spinning wheel before the channels load successfully.

Large Server: Selecting this server results in an extended spinning wheel, followed by the error. The only error I've managed to identify is related to running out of memory.

Small server has less than 100 channels.
Large server has 614.

Any suggestions for me?  I'm going to try deploying on WIndows server just to see if it works better over there, but in my environment, it will ultimately have to be Linux, as we don't support Windows in the environment.

Thanks so much for the responses!
-Jim

**Comment by odoodo** [comment]
At which destination of the channel does the issue appear? Are you using a lot of templates in your channels?
Please try [this build](https://github.com/user-attachments/files/18757773/MirthMigrato.jar-cuttingTemplatesInChannels.zip). It cuts templates from the channels before parsing and should thus reduce memory footprint.

If this doesn't help, you might want to increase the log level of the library to debug. That way Mirth Migrator becomes really talking.

**Comment by jwhowa-rp** [comment]
> MirthMigrato.jar-cuttingTemplatesInChannels.zip). It cuts templates from the channels before parsing and should thus reduce memory footprint.

I'll try that late this afternoon and advise, thank you sir!

**Comment by jwhowa-rp** [comment]
MirthMigrato.jar-cuttingTemplatesInChannels.zip didn't really change anything for me, it still works on low volume servers but gags on high volume.  I'm working with an internal Mirth developer to give you more information, my area of expertise is in release management. :)   

I don't know if this is helpful or not, but here's the error:

![Image](https://github.com/user-attachments/assets/29bb2657-1ef3-4c03-862c-6e88397be695)

Thanks!
-Jim

**Comment by odoodo** [comment]
> I don't know if this is helpful or not, but here's the error:

Unfortunately this does not show the error but the mappings. But it indicates that the error occurred in the destination "getComponentMetaData".

The error details can be found under the **Error-tab** next to the Mappings-tab:
![Image](https://github.com/user-attachments/assets/e1c90fe6-1cee-4b65-bbce-6532ce3b8227)

In order for Mirth to display all information, the log level must be adjusted. This is done in the **Summary** tab of the channel. Set **Message Storage** to **"Production"**:
![Image](https://github.com/user-attachments/assets/ef2c255e-77f9-45cb-b624-28829c974b08)

Please redeploy the channel after the adaption, trigger the error and post the content of the error-tab.

**Comment by jwhowa-rp** [comment]
I have done so, the only error I see is very unhelpful:

> Transformer error
> ERROR MESSAGE: Error evaluating transformer
> java.lang.OutOfMemoryError: Java heap space

I currently have java heap set at 4gb to be ridiculously supportive. :)

It is interesting (to me anyway) to note that on my "big system" that gags with the 200 error and causes the error, that only happens when I try to pull channels.  Pulling code template works.

**Comment by odoodo** [comment]
It's very hard to track down the issue as I cannot reproduce it. 
Please increase the log level of the Mirth Migrator library as described [here](https://github.com/odoodo/Mirth-Migrator/discussions/8). Afterwards you would have to restart the Mirth service.

This might provide some deeper insights.

**Comment by jwhowa-rp** [comment]
You know what -- You're going to hate me.  I have been increasing the heap size on the vmservice file not the vmserver file.  I noticed that 2 character difference just now and fixed it.  With your latest code, I can confirm it *does* now pull in all my channels or code templates on a large server.  

I currently have the heap size at 4gb, will be pulling it down until I find a number that doesn't break, and advise!

Sorry to have sent you rabbit-chasing!

**Comment by pacmano1** [comment]
Jim, Jim, Jim... (read it aloud like your grammar school teacher might have).

**Comment by jwhowa-rp** [comment]
> Jim, Jim, Jim... (read it aloud like your grammar school teacher might have).

Oh message received!!!!! :D :D :D

**Comment by odoodo** [comment]
Great to see that you got your issue fixed! I assume 2GB should be more than enough even for the largest server.
